In [25]:
import numpy as np
import pandas as pd

In [26]:
from sklearn.preprocessing import OneHotEncoder

In [27]:
Countries=[["India","China","Russia"],["China","Russia","India"]]

In [21]:
encoder = OneHotEncoder(sparse=False, handle_unknown='ignore')

In [28]:
Countries_2d= np.array(Countries).reshape(-1,1)
Countries_2d

array([['India'],
       ['China'],
       ['Russia'],
       ['China'],
       ['Russia'],
       ['India']], dtype='<U6')

In [29]:
one_hot_encoded = encoder.fit_transform(Countries_2d)
print(one_hot_encoded)

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]
